import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Map from "../components";
import Link from "next/link";
import Carousel from "@/components/UI/Carousel/Carousel";

export default function Home() {

  const API_URL = 'https://us-central1-augmented-axe-380213.cloudfunctions.net/seass_bigquery';

  const submitHandler = async () => {
    const response = await fetch(`${API_URL}`);
    const data = await response.json();
    console.log(data.result);
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet-heat/0.2.0/leaflet-heat.js"></script>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      <button onClick={submitHandler}>Click me!</button>
        {/* <Carousel /> */}
        <Map />
      </main>
    </>
  );
}
